In [1]:
import numpy as np
import pandas as pd

In [2]:
!pip install emoji

     |████████████████████████████████| 170 kB 5.5 MB/s 
  Created wheel for emoji: filename=emoji-1.6.1-py3-none-any.whl size=169314 sha256=bab05e7bf872fa5d8b8f3e7ffb89ea3b915b6e6fb2bb2370ad30e2bef19cd177
  Stored in directory: /root/.cache/pip/wheels/ea/5f/d3/03d313ddb3c2a1a427bb4690f1621eea60fe6f2a30cc95940f
Successfully built emoji


In [3]:
import emoji

In [4]:
emoji.EMOJI_UNICODE['en']

{':1st_place_medal:': '🥇',
 ':2nd_place_medal:': '🥈',
 ':3rd_place_medal:': '🥉',
 ':AB_button_(blood_type):': '🆎',
 ':ATM_sign:': '🏧',
 ':A_button_(blood_type):': '🅰️',
 ':Afghanistan:': '🇦🇫',
 ':Albania:': '🇦🇱',
 ':Algeria:': '🇩🇿',
 ':American_Samoa:': '🇦🇸',
 ':Andorra:': '🇦🇩',
 ':Angola:': '🇦🇴',
 ':Anguilla:': '🇦🇮',
 ':Antarctica:': '🇦🇶',
 ':Antigua_&_Barbuda:': '🇦🇬',
 ':Aquarius:': '♒',
 ':Argentina:': '🇦🇷',
 ':Aries:': '♈',
 ':Armenia:': '🇦🇲',
 ':Aruba:': '🇦🇼',
 ':Ascension_Island:': '🇦🇨',
 ':Australia:': '🇦🇺',
 ':Austria:': '🇦🇹',
 ':Azerbaijan:': '🇦🇿',
 ':BACK_arrow:': '🔙',
 ':B_button_(blood_type):': '🅱️',
 ':Bahamas:': '🇧🇸',
 ':Bahrain:': '🇧🇭',
 ':Bangladesh:': '🇧🇩',
 ':Barbados:': '🇧🇧',
 ':Belarus:': '🇧🇾',
 ':Belgium:': '🇧🇪',
 ':Belize:': '🇧🇿',
 ':Benin:': '🇧🇯',
 ':Bermuda:': '🇧🇲',
 ':Bhutan:': '🇧🇹',
 ':Bolivia:': '🇧🇴',
 ':Bosnia_&_Herzegovina:': '🇧🇦',
 ':Botswana:': '🇧🇼',
 ':Bouvet_Island:': '🇧🇻',
 ':Brazil:': '🇧🇷',
 ':British_Indian_Ocean_Territory:': '🇮🇴',
 ':British_Virgin_

In [5]:
emoji_dict = {
    
    "0" : ':beating_heart:',
    "1" : ':basketball:',
    "2" : ':beaming_face_with_smiling_eyes:',
    "3" : ':anxious_face_with_sweat:',
    "4" : ':banana:'
}

In [6]:
for e in emoji_dict.values():
    print(emoji.emojize(e) , end = " ")

💓 🏀 😁 😰 🍌 

In [7]:
train = pd.read_csv("/content/train_emoji.csv",header = None)
test = pd.read_csv("/content/test_emoji.csv",header = None)

In [8]:
train.drop(columns=[2,3], inplace=True)

In [12]:
train.head()

0  1
0           never talk to me again  3
1  I am proud of your achievements  2
2   It is the worst day in my life  3
3                 Miss you so much  0
4                     food is life  4

In [14]:
test[0]  = test[0].apply(lambda x : x[:-1])

In [15]:
test.head()

0  1
0             I want to eat  4
1         he did not answer  3
2            he got a raise  2
3      she got me a present  0
4  ha ha ha it was so funny  2

In [9]:
X_train = train[0].values
y_train = train[1].values

X_test = test[0].values
y_test = test[1].values

In [16]:
X_train[:5]

array(['never talk to me again', 'I am proud of your achievements',
       'It is the worst day in my life', 'Miss you so much',
       'food is life'], dtype=object)

In [17]:
y_train[:10]

array([3, 2, 3, 0, 4, 0, 3, 2, 3, 1])

In [18]:
X_train.shape,y_train.shape

((132,), (132,))

In [19]:
X_test.shape,y_test.shape

((56,), (56,))

In [20]:
for i in range(20, 35):
    print(X_train[i], emoji.emojize( emoji_dict[str(y_train[i])]) )

So sad you are not coming 😰
She is my dearest love 💓
Good job 😁
It was funny lol 😁
candy is life  😁
The chicago cubs won again 🏀
I am hungry 🍌
I am so excited to see you after so long 😁
you did well on you exam 😁
lets brunch some day 🍌
he is so cute 💓
How dare you ask that 😰
do you want to join me for dinner  🍌
I said yes 😁
she is attractive 💓


#Get embeddings

In [21]:
f = open("/content/glove.6B.50d.txt", encoding ='utf8' , mode='r')

In [ ]:
#f.read()

In [22]:
embedding_matrix = { }

In [23]:
for line in f :
  values = line.split()
 # print(values)
  word = values[0]
  emb = np.array(values[1:],dtype = 'float')
  embedding_matrix[word] = emb

In [26]:
embedding_matrix['question'].shape

(50,)

In [28]:
def get_embedding_matrix_for_data(data):
    maxLen = 10
    embedding_data = np.zeros( (len(data), maxLen, 50) )
    
    for ix in range(data.shape[0]):
        words_in_sen = data[ix].split()
        
        for ij in range(len(words_in_sen)):
            if embedding_matrix.get(words_in_sen[ij].lower()) is not None:
                embedding_data[ix][ij] =  embedding_matrix[words_in_sen[ij].lower()]
        
    return embedding_data

In [29]:
X_train = get_embedding_matrix_for_data(X_train)

In [30]:
X_test = get_embedding_matrix_for_data(X_test)

In [31]:
X_train.shape

(132, 10, 50)

In [32]:
X_test.shape

(56, 10, 50)

In [33]:
from tensorflow.keras.utils import to_categorical

In [34]:
y_train = to_categorical(y_train)
y_test = to_categorical(y_test)

In [35]:
y_train.shape


(132, 5)

In [36]:
y_test.shape

(56, 5)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, SimpleRNN, Dense, Dropout

In [38]:
model = Sequential()
model.add( LSTM(units=64, input_shape=(10,50), return_sequences = True ) )
model.add( Dropout(0.3) )
model.add( LSTM(units=32) )
model.add(Dropout(0.2))
model.add(Dense(units=10, activation = 'relu'))
model.add(Dense(units=5, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm (LSTM)                 (None, 10, 64)            29440     
                                                                 
 dropout (Dropout)           (None, 10, 64)            0         
                                                                 
 lstm_1 (LSTM)               (None, 32)                12416     
                                                                 
 dropout_1 (Dropout)         (None, 32)                0         
                                                                 
 dense (Dense)               (None, 10)                330       
                                                                 
 dense_1 (Dense)             (None, 5)                 55        
                                                                 
Total params: 42,241
Trainable params: 42,241
Non-traina

In [39]:
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics= ['accuracy'])

In [40]:
his = model.fit(X_train, y_train, validation_split=0.1, batch_size=32, epochs= 50 )

Epoch 1/50
4/4 [==============================] - 12s 386ms/step - loss: 1.6113 - accuracy: 0.2542 - val_loss: 1.5823 - val_accuracy: 0.2857
Epoch 2/50
4/4 [==============================] - 0s 21ms/step - loss: 1.5695 - accuracy: 0.3305 - val_loss: 1.5895 - val_accuracy: 0.0714
Epoch 3/50
4/4 [==============================] - 0s 20ms/step - loss: 1.5207 - accuracy: 0.3475 - val_loss: 1.6023 - val_accuracy: 0.0714
Epoch 4/50
4/4 [==============================] - 0s 20ms/step - loss: 1.4929 - accuracy: 0.3136 - val_loss: 1.6113 - val_accuracy: 0.0714
Epoch 5/50
4/4 [==============================] - 0s 20ms/step - loss: 1.4584 - accuracy: 0.3644 - val_loss: 1.5997 - val_accuracy: 0.2143
Epoch 6/50
4/4 [==============================] - 0s 22ms/step - loss: 1.4210 - accuracy: 0.3729 - val_loss: 1.5577 - val_accuracy: 0.2143
Epoch 7/50
4/4 [==============================] - 0s 22ms/step - loss: 1.3644 - accuracy: 0.4153 - val_loss: 1.5287 - val_accuracy: 0.2143
Epoch 8/50
4/4 [=========

In [41]:
model.evaluate(X_train, y_train)

5/5 [==============================] - 0s 17ms/step - loss: 0.1165 - accuracy: 0.9697


[0.11647763848304749, 0.9696969985961914]

In [42]:
model.evaluate(X_test , y_test)

2/2 [==============================] - 0s 14ms/step - loss: 1.4965 - accuracy: 0.6071


[1.4965051412582397, 0.6071428656578064]

#predection

In [43]:
y_pred = np.argmax(model.predict(X_test), axis=-1)

In [44]:
y_pred

array([4, 3, 3, 2, 2, 2, 3, 2, 4, 2, 1, 2, 0, 3, 1, 3, 3, 2, 3, 2, 0, 0,
       4, 3, 3, 3, 2, 0, 1, 2, 0, 1, 0, 2, 0, 1, 2, 3, 4, 2, 1, 0, 0, 1,
       2, 2, 2, 2, 3, 1, 1, 3, 3, 2, 2, 3])

In [45]:
np.argmax(y_test, axis=1)

array([4, 3, 2, 0, 2, 0, 0, 0, 4, 2, 1, 3, 3, 2, 1, 3, 3, 2, 3, 4, 0, 2,
       4, 3, 3, 3, 3, 0, 2, 0, 0, 1, 3, 2, 0, 1, 2, 4, 4, 2, 2, 2, 0, 1,
       2, 0, 2, 2, 2, 3, 3, 0, 3, 2, 2, 3])

In [46]:
for t in range(len(test)):
    print(test[0].iloc[t])
    print("Prediction : ",  emoji.emojize(emoji_dict[str(y_pred[t])]) )
    print("Actual : ", emoji.emojize(emoji_dict[str( test[1].iloc[t] )]) )
    print()
    print()

I want to eat
Prediction :  🍌
Actual :  🍌


he did not answer
Prediction :  😰
Actual :  😰


he got a raise
Prediction :  😰
Actual :  😁


she got me a present
Prediction :  😁
Actual :  💓


ha ha ha it was so funny
Prediction :  😁
Actual :  😁


he is a good friend
Prediction :  😁
Actual :  💓


I am upset
Prediction :  😰
Actual :  💓


We had such a lovely dinner tonight
Prediction :  😁
Actual :  💓


where is the food
Prediction :  🍌
Actual :  🍌


Stop making this joke ha ha ha
Prediction :  😁
Actual :  😁


where is the ball
Prediction :  🏀
Actual :  🏀


work is hard
Prediction :  😁
Actual :  😰


This girl is messing with me
Prediction :  💓
Actual :  😰


are you serious ha ha
Prediction :  😰
Actual :  😁


Let us go play baseball
Prediction :  🏀
Actual :  🏀


This stupid grader is not working 
Prediction :  😰
Actual :  😰


work is horrible
Prediction :  😰
Actual :  😰


Congratulation for having a baby
Prediction :  😁
Actual :  😁


stop messing around
Prediction :  😰
Actual :  😰


any sugges

In [ ]:
#model.evaluate(X_train,y_train)[1*100]

#prediction for custom input

In [47]:
inp  = "i am hungry"

In [48]:
inp

'i am hungry'

In [49]:
embedding_x_query = []

In [50]:
for w in inp.lower().split():
    print(w)
    e = embedding_matrix[w]
    embedding_x_query.append(e)

i
am
hungry


In [51]:
embedding_x_query = np.array(embedding_x_query)

In [52]:
embedding_x_query.shape

(3, 50)

In [53]:
if embedding_x_query.shape[0] < 10:
    embedding_x_query = np.vstack( (embedding_x_query, np.zeros((10 - len(embedding_x_query) , 50))  ) )

In [54]:
embedding_x_query.shape

(10, 50)

In [55]:
embedding_x_query = embedding_x_query.reshape(1, 10, 50)

In [56]:
embedding_x_query.shape

(1, 10, 50)

In [57]:
pred = np.argmax(model.predict(embedding_x_query), axis=-1)

In [58]:
emoji.emojize( emoji_dict[ str(pred[0])] )

'🍌'